[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = /dev/ttyUSB0

; Serial Monitor Baudrate
monitor_speed = 115200

; Library dependencies
lib_deps =
    adafruit/Adafruit PN532 
    madhephaestus/ESP32Servo 
    bblanchon/ArduinoJson
    https://github.com/marcoschwartz/LiquidCrystal_I2C.git